package Aplicacio;

public class main {

	public static void main(String[] args) {
		// TODO Auto-generated method stub

	}
	
	//RAMA 1- PLANTA-ARBUSTO-ARBOL-LISTAPLANTAS (CRISTHIAN)
	//RAMA 2- PLANTACIONS-LLISTA PLANTACIONS (ARNAU)
	//RAMA 3- TipusTerreny-RODAL-LISTATIPUSTERRENY (NAHUEL)
	//RAMA 4- MAIN GLOBAL Y GRAFICO (ADRI)

}
//VALE VALE VALE A VER
//HABEIS VISTo????
//SE A ACTUALIZADO A TU RAMA SOLO, esta vacia
//NO MIRA, ARNAU ENTRA EN LA RAMA MAIN
//Y LUEGO ENTRA EN LA TUYA A VER SI TE CAMBIAN LOS ARCHIVOS, SI
//no, VA MAL xd